### ISSUE TITLE
Tried to set the air on fire... This is bad.

### ISSUE THREAD

**Issue by 4rz0** [ReikaKalseki/LegacyCraft#3]
With *B:"Original Fire Spread"=true* activated, Minecraft crashes with following log:
http://www.hastebin.com/fuvaqibode.profile

Minecraft 1.7.10
forge 10.13.2.1231
DragonAPI 1.7.10 V2
LegacyCraft 1.7.10 V2

**Comment by ReikaKalseki** [comment]
Fixed in v3.
